@url=https://10.80.42.223:8090

@json=Content-Type: application/json

###
get {{url}}


###
post {{url}}/register
{{json}}

{
    "username": "cycyes",
    "password": "cycyes"
}


###
post {{url}}/login
{{json}}

{
    "username": "user2",
    "password": "123456"
}


###
get {{url}}/profile

###
post {{url}}/logout

###
get {{url}}/listenuser